### ISSUE TITLE
Individual commands to switch between stats, tasks and settings tab

### ISSUE THREAD

**Issue by artlee06** [AY1920S2-CS2103T-W16-1/main#112]

**Comment by Permas-Teo** [comment]
Not a trivial problem I think? 

Possible start:
Right now tabs are linked to the fxml on MainWindow.java. Your job will be to link the TabPane instead of the tabs, then create command/s to call the following functions.

https://stackoverflow.com/questions/20955633/how-to-switch-through-tabs-programmatically-in-javafx
